version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./whoami.local:/etc/nginx/htpasswd/whoami.local

  whoami:
    image: jwilder/whoami
    environment:
      VIRTUAL_HOST: whoami.local
